import { ExercisesContextProvider } from '@/modules/data/hooks/exercises-context';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Fitness Tracker</title>
        <meta name="Nescription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExercisesContextProvider>
        <Component {...pageProps} />
      </ExercisesContextProvider>
    </>
  );
}
